server:
  port: 8083

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/rentaldb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

clients:
  user-service:
    base-url: ${USER_SERVICE_URL:http://localhost:8081}
  vehicle-service:
    base-url: ${VEHICLE_SERVICE_URL:http://localhost:8082}
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

