server:
  port: 8084

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/listingdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  application:
    name: listing-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

clients:
  vehicle-service:
    base-url: ${VEHICLE_SERVICE_URL:http://localhost:8082}

security:
  jwt:
    secret: ${JWT_SECRET:VGhpc0lzQVN0cm9uZ0RldmVsb3BtZW50S2V5VGhpc0lzQVN0cm9uZ0RldmVsb3BtZW50S2V5}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
