server:
  port: 8086

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/paymentdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  application:
    name: payment-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
