server:
  port: 8081

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/userdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
security:
  jwt:
    secret: ${JWT_SECRET:VGhpc0lzQVN0cm9uZ0RldmVsb3BtZW50S2V5VGhpc0lzQVN0cm9uZ0RldmVsb3BtZW50S2V5}
    expiration-seconds: ${JWT_EXPIRATION_SECONDS:3600}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

